apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: apache-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache-server
  template:
    metadata:
      labels:
        app: apache-server
    spec:
      containers:
      - name: apache-server
        image: httpd:2.4.59
        ports:
        - containerPort: 80
